drop table if exists demo_record;

create table demo_record (
    id bigint generated by default as identity primary key,
    title varchar(128) not null,
    content varchar(512),
    status varchar(32) not null,
    version integer not null,
    tenant_id bigint,
    dept_id bigint,
    create_by bigint,
    update_by bigint,
    create_time timestamp,
    update_time timestamp
);
